from rest_framework.exceptions import ValidationError


class OwnershipError(ValidationError):
    pass
